source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'mysql2', '< 0.3'
gem 'jquery-rails'
gem 'omniauth'
gem 'oauth'
gem 'oa-openid', :require => 'omniauth/openid' 
gem 'haml'
gem 'compass'
gem 'carrierwave'
gem 'rmagick'
gem 'spreadsheet'
